### ISSUE TITLE
Bad list numbering in epub

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#10]
The bullets in the numbered list in section "A Brief Sony Password Analysis" (criteria for analysis) are all numbered *1*, see following screenshot:

![Screenshot_20220830-223845_ReadEra](https://user-images.githubusercontent.com/15836594/187539553-ced2ba04-4a49-4354-84ee-aab378ef447d.jpg)

It's V0.1 (ePub), and I'm using the [ReadEra](https://play.google.com/store/apps/details?id=org.readera) app on a Galaxy S22 with Android 12

**Comment by troyhunt** [comment]
That's odd, it's good in the source post: https://www.troyhunt.com/brief-sony-password-analysis/

But it may be that I fixed it *after* @robconery grabbed it for the book, I had a bunch of ordered lists no longer order after a blog upgrade years ago.

**Comment by rose-a** [comment]
It's ok in the PDF version, too... Seems to be an ePub issue

**Comment by rose-a** [comment]
Found another one:

![Screenshot_20220831-214000_ReadEra](https://user-images.githubusercontent.com/15836594/187767936-31d85e06-911e-4c3d-9a31-16691fc0c695.jpg)

**Comment by robconery** [comment]
That is the weirdest thing - in both cases the lists looked good in the parent document but it looks like they've been reformatted by the Android reader. I cleared all formatting and redid so hopefully that fixes the issue.
