### ISSUE TITLE
Incorrect spelling

### ISSUE THREAD

**Issue by HandeTech** [robconery/troys-book#105]
## Where'd you find this? Page number from PDF would be helpful
xx
## What's the problem? 
Incorrect spelling, last paragraph, 2nd line, 5th word.
FWIW, also in last paragraph and last word of line four. Perhaps that numeric character should be as an alpha?
This is what I read:
```md
//put it in here
carriers
```
This is what I think it should be:
```md
//put it in here
carries
```
## How are you reading the book?
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)
Win10, PDF, Version 0.3. Note, have only read to page xxi

**Comment by troyhunt** [comment]
I think there's a couple of bits missing there, what's the page number?

**Comment by HandeTech** [comment]
Well, there's two page numbers because the page number is xx in the book on penultimate page of your Introduction, however PDF page count reads page 21.

**Comment by troyhunt** [comment]
Ah, I see now. At this point we're a bit beyond making edits to the book itself, but thank you anyway for reporting it.

**Comment by HandeTech** [comment]
No worries Troy, all good and understood. Cheers and all the best.
