### ISSUE TITLE
Typo: I submitted a couple or proposed talks

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#13]
## Where'd you find this? Page number from PDF would be helpful
Intro of "NDC 2014, Vikings, Passwords and Pineapples (and Session Videos)"

## What's the problem? 

This is what I read:
```md
I submitted a couple or proposed talks
```

This is what I think it should be:
```md
I submitted a couple of proposed talks
```
## How are you reading the book?
epub, V0.1, ReadEra app on Android

**Comment by robconery** [comment]
Thanks fixed!
