### ISSUE TITLE
Typo: I’d never expected to come fact to face with

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#14]
## Where'd you find this? Page number from PDF would be helpful
Intro of "NDC 2014, Vikings, Passwords and Pineapples (and Session Videos)"

## What's the problem? 

This is what I read:
```md
I’d never expected to come fact to face with
```

This is what I think it should be:
```md
I’d never expected to come face to face with
```
## How are you reading the book?
epub, V0.1

**Comment by robconery** [comment]
Thanks - fixed!
