### ISSUE TITLE
epub Formatting: indented text reaches beyond right border

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#15]
![Screenshot_20220831-214000_ReadEra](https://user-images.githubusercontent.com/15836594/187768739-a57de491-5f1f-44af-b30d-75adadc2dd35.jpg)

Gets even worse when disabling padding in the app:

![Screenshot_20220831-214705_ReadEra](https://user-images.githubusercontent.com/15836594/187768907-db904cff-1ba2-4dcf-9435-7bf6d3cf3e25.jpg)

## Where
In the blog post "NDC 2014, Vikings, Passwords and Pineapples (and Session Videos)"

epub v0.1, ReadEra app on Android

**Comment by robconery** [comment]
Cheers thanks - I _think_ I got it to layout better; my preview looks OK but I don't have an Android device. I think it was some old formatting that was left in place.
