### ISSUE TITLE
Formatting error in "comments" section

### ISSUE THREAD

**Issue by rutherglendee** [robconery/troys-book#16]
## Where'd you find this? Page number from PDF would be helpful

Hi, 
Page 89 of the PDF copy. "Find my car" blog post. At the end of the "comments" section there's a paragraph from Troy "For this app they ...". It is italicised but I think it's meant not to be since it's Troy's response. Also "Troy:" is normally in bold.

```
## How are you reading the book?
Book version 0.1
PDF 
Being read on Windows 10

**Comment by robconery** [comment]
Great! Thanks - fixed :).
