### ISSUE TITLE
Congress should have capital C

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#17]
## Where'd you find this? Page number from PDF would be helpful
XII
## What's the problem? 
Congress should have a capital C, and should be named appropriately. Am aware that this is part of the foreword though
This is what I read:
```md
testifying in front of the congress of the United States
```

This is what I think it should be:
```md
 testifying in front of the United States Congress
```
## How are you reading the book?
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)
PDF - 0.1

**Comment by robconery** [comment]
I mean honestly... what would Lars know about the US congress anyway.... (fixed)
