### ISSUE TITLE
Typo: have absolutely no desire the personal information

### ISSUE THREAD

**Issue by robconery** [robconery/troys-book#2]
There is a typo on Page 29, it read: "have absolutely no desire the see personal information"
When I think it should be: "have absolutely no desire to see personal information"

[added by Rob for another user]

**Comment by l3v1tat3** [comment]
Oh, I see. I understand how that could be difficult.
In my opinion, I'd say fix the typo, as if a curious reader really wants to, they could always go back and read the original on Troy's blog.

**Comment by robconery** [comment]
Fixed in book - @troyhunt you might want to update the Ashley Madison post

**Comment by troyhunt** [comment]
Thanks all, now fixed in source.
