### ISSUE TITLE
Wrong word used?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#20]
## Where'd you find this? Page number from PDF would be helpful
166
## What's the problem? 
Incorrect word used?
This is what I read:
```md
absolutely no desire the see personal information
```

This is what I think it should be:
```md
absolutely no desire to see personal information
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
Already fixed here: https://github.com/robconery/troys-book/issues/2
