### ISSUE TITLE
Spelling mistake?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#23]
## Where'd you find this? Page number from PDF would be helpful
212
## What's the problem? 
Includes page number in word
This is what I read:
```md
212rganization
```

This is what I think it should be:
```md
organization
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
This one is definitely on you @robconery! Original comment is not only spelled correctly, but the correct *Australian* way! https://www.troyhunt.com/controlling-vehicle-features-of-nissan/#comment-2533656762

**Comment by thecrmninja** [comment]
I was indeed wondering about the spelling of it as well, but thought I'd not point that part out ;)

**Comment by robconery** [comment]
Ha ha I blame... SUNSPOTS (fixed)
