### ISSUE TITLE
Grammar issue?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#24]
## Where'd you find this? Page number from PDF would be helpful
249
## What's the problem? 
Word should possibly be in the plural?
This is what I read:
```md
there goes 5 day
```

This is what I think it should be:
```md
there goes 5 days
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
This is a typo in my own comment on the original post. @robconery, Disqus won't let me edit the original comment 6 years on, leave it to you if you fix in the book or just close this issue out.

**Comment by robconery** [comment]
Yep fixed
