### ISSUE TITLE
Wrong word used?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#25]
## Where'd you find this? Page number from PDF would be helpful
280
## What's the problem? 
Believe wrong word has been used
This is what I read:
```md
without and need
```

This is what I think it should be:
```md
without a need
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
I've fixed this in source and updated it to "without *the* need".

**Comment by robconery** [comment]
Same fixed - thanks
