### ISSUE TITLE
Seems to be an unnecessary line break on P.551?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#26]
## What device are you reading this on?
PC
## How are you reading the book?
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)
PDF - 0.1
## Screenshot
![image](https://user-images.githubusercontent.com/71081526/188853487-c60d1b5d-9567-4669-965d-3ddb970d2872.png)

**Comment by robconery** [comment]
Rad thanks! Fixed :)
