### ISSUE TITLE
Word should be in the plural?

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#27]
## Where'd you find this? Page number from PDF would be helpful
569
## What's the problem? 
'Example' is in the singular, but I think it should be in the plural?
This is what I read:
```md
(I've been dropping example into it since Xmas!)
```

This is what I think it should be:
```md
(I've been dropping examples into it since Xmas!)
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
Awesome, now fixed in the source post.

**Comment by robconery** [comment]
Fixed@
