### ISSUE TITLE
Additional letter/word not needed

### ISSUE THREAD

**Issue by thecrmninja** [robconery/troys-book#29]
## Where'd you find this? Page number from PDF would be helpful
821
## What's the problem? 
Additional letter/word 'a'
This is what I read:
```md
Bear with me as a I navigate my own
```

This is what I think it should be:
```md
Bear with me as I navigate my own
```
## How are you reading the book?
PDF - 0.1

**Comment by troyhunt** [comment]
Good find! Now fixed in the source post.

**Comment by robconery** [comment]
Fixed!
