### ISSUE TITLE
Typo: a Microsoft Word in Intro

### ISSUE THREAD

**Issue by saintsim** [robconery/troys-book#3]
## Where'd you find this? Page number from PDF would be helpful
Page 3 (Introduction)

## What's the problem? 

This is what I read:
```md
I was teaching people how to use a Microsoft Word and run Encyclopaedia Britannica off a CD
```

This is what I think it should be (remove the **_a_** before Microsoft):
```md
I was teaching people how to use Microsoft Word and run Encyclopaedia Britannica off a CD
```
## How are you reading the book?
PDF, I don't see a version but this is a copy downloaded on 31st October 2021

**Comment by robconery** [comment]
Cheers thanks - this was fixed in a recent update. Appreciate you letting us know!
