### ISSUE TITLE
Typo: I'd have a post explaining why they was wrong

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#30]
## Where'd you find this? Page number from PDF would be helpful
Intro of "The Effectiveness of Publicly Shaming Bad Security"

## What's the problem? 

This is what I read:
```md
I'd have a post explaining why they was wrong.
```

This is what I think it should be:
```md
I'd have a post explaining why they were wrong.
```
## How are you reading the book?
ePub, V0.1

**Comment by robconery** [comment]
Thanks :)
