### ISSUE TITLE
Tesco typo

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#33]
## Where'd you find this? Page number from PDF would be helpful
103
## What's the problem? 
During the Tesco error page part the word `so` instead of `to` is used.

This is what I read:
```md
3.An internal server error is returned because although the trace handler
can't be displayed, the site is not configured so show friendly error
messages. It looks exactly like this:
```

This is what I think it should be:
```md
3.An internal server error is returned because although the trace handler
can't be displayed, the site is not configured to show friendly error
messages. It looks exactly like this:
```
## How are you reading the book?
Windows  PDF version 0.1

**Comment by troyhunt** [comment]
Good find! Now fixed at the source.
