### ISSUE TITLE
HIBP acronym with no context

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#34]
## Where'd you find this? Page number from PDF would be helpful
Multiple places

## What's the problem? 
In the book, there are segments where "Have I been Pwned" is used and at other times "HIBP". There doesn't appear to be a point where the text puts the two parts together such as "Have I been Pwned (HIBP)" which would help people realise this is what the acronym relates to.

**Comment by troyhunt** [comment]
My inclination is to leave this as is. The context of HIBP is outlined pretty clearly in the intro and historically, I've oscillated between acronyms, full name and a combination of the 2. I don't think anyone is coming away confused by any of those combinations.
