### ISSUE TITLE
Grammar (two items)

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#38]
This is what I read: 
>I spen***d*** a bit of time writing about how people and software manage 
passwords and often talk about thing like entropy 

This is what I think it should be:
>I spen***t*** a bit of time writing about how people and software manage 
passwords and often talk about thing***s*** like entropy 

pdf version 001 page 59, reading with Edge on Windows 11

**Comment by robconery** [comment]
I think @troyhunt is trying to say he actively spends time doing these things. Going to let this one go.

**Comment by troyhunt** [comment]
Agree with @robconery on this one.
