### ISSUE TITLE
Here’s how I handle online abuse - Comments missing 's'

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#39]
## Where'd you find this? Page number from PDF would be helpful
272

## What's the problem? 
Should read `5 days` instead of `5 day`

This is what I read:
```
Now as an independent, if I even do just a 1 hour talk overseas
I'm pretty much taking a week off from earning money because everything is so
far away from Australia, then you add jet lag and recovery and there goes 5 day.
```

This is what I think it should be:
```
Now as an independent, if I even do just a 1 hour talk overseas
I'm pretty much taking a week off from earning money because everything is so
far away from Australia, then you add jet lag and recovery and there goes 5 days.
```
## How are you reading the book?
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)
Windows 11 - PDF - Version 0.1

**Comment by troyhunt** [comment]
Good spot, but that's in a comment which we're generally not changing (even though it's mine!) I actually can't even edit it at the source, not sure why Disqus isn't allowing that.
