### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#40]
This is what I read: 
>the number plate***s*** – and this is what I'm really talking about when I say "privacy" – appears to be indiscernible 

This is what I think it should be:
>the number plate – and this is what I'm really talking about when I say "privacy" – appears to be indiscernible

Use either the singular or the plural; mixing them looks a little odd to me
Use "the plate appears" or "the plates appear"

pdf version 001 page 77, reading with Edge on Windows 11

**Comment by troyhunt** [comment]
Partly agree with this one: "plates" should be plural because there are many in the image, but that means that "appears to be indiscernible" should be changed to "appear to be...". I've now fixed that in source, @robconery will fix in the book.
