### ISSUE TITLE
Apostrophe

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#42]
This is what I read: 
>the "fraudulent" use of the act in terms of it***s'*** use for ...

This is what I think it should be:
>the "fraudulent" use of the act in terms of its use for ...

and yes, a stray apostrophe is probably nit-picking! Couldn't resist it...

pdf version 001 page 113, reading with Edge on Windows 11

**Comment by troyhunt** [comment]
Not nit-picking at all, thank you! Fixed in source now, @robconery will fix it in the book.
