### ISSUE TITLE
Typo in chapter "HERE’S EVERYTHING THAT GOES INTO A MASSIVE INTERNATIONAL SPEAKING TRIP"

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#44]
## Where'd you find this? Page number from PDF would be helpful
279

## What's the problem? 
Should be 'in' instead of 'is'

This is what I read:
```
With all that and a carry-on bag for clothes, I can go from the car to sitting in the domestic lounge is 5 minutes tops
```

This is what I think it should be:
```
With all that and a carry-on bag for clothes, I can go from the car to sitting in the domestic lounge in 5 minutes tops
```
## How are you reading the book?
Windows 11, PDF v0.1

**Comment by troyhunt** [comment]
Good one, fixed in source, over to @robconery for the book.
