### ISSUE TITLE
Incomplete sentence in chapter "Here’s everything that goes into a massive international speaking trip"

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#45]
## Where'd you find this? Page number from PDF would be helpful
310

## What's the problem? 
Seems like there's some missing words/sentence 
This is what I read:
```md
At breakfast to catch up on some backlog. 
```

## How are you reading the book?
Windows 11 PDF v0.1

**Comment by troyhunt** [comment]
Agreed, it should begin with:

> I'm at breakfast

Fixed in source, over to @robconery for the book.
