### ISSUE TITLE
missing word "in"?

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#46]
This is what I read: 
> in part so as not to disclose personal information about Jan and part because ...

This is what I think it should be:
> in part so as not to disclose personal information about Jan and **in** part because ...

or perhaps:
> **partly** so as not to disclose personal information about Jan and **partly** because ...

pdf version 001 page 211, reading with Edge on Windows 11

**Comment by troyhunt** [comment]
Cheers, fixed at source with a very slight variation:

> in part so as not to disclose personal information about Jan and **in** part

@robconery will fix in the book.
