### ISSUE TITLE
On the one had (hand)

### ISSUE THREAD

**Issue by Cyber246** [robconery/troys-book#5]
On both epub and pdf as per debut day 26-Aug-2023

![EDD428C7-E505-445E-BB3F-8F55FAFB8E6D](https://user-images.githubusercontent.com/112099682/186694632-4a4aed61-c5b1-465f-b0ef-681d4f118eab.jpeg)

**Comment by troyhunt** [comment]
I'm actually really impressed that it's taken 13 years to report a typo in my oldest ever blog post! I've fixed it at the source, just discussing with @robconery if this is the sort of thing we want to continually fix in the book itself or we just leave fixes to the new intro and epilogue bits. Either way, thanks for finding this 😊

**Comment by robconery** [comment]
Fixed!
