### ISSUE TITLE
`any` instead of `and` in chapter "Here’s everything that goes into a massive international speaking trip"

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#51]
## Where'd you find this? Page number from PDF would be helpful
328

## What's the problem? 
Should be `and` instead of `any`
This is what I read:
```
This is the part of being away that really sucks and any remaining gloss that was
on the idea of international travel is well any truly gone.
```

This is what I think it should be:
```
This is the part of being away that really sucks and any remaining gloss that was
on the idea of international travel is well and truly gone.
```
## How are you reading the book?
Windows 11 PDF v0.1

**Comment by troyhunt** [comment]
This just felt like an awkward sentence so I've rewritten it as follows in source:

> This is the part of being away that *really* sucks any remaining gloss off the notion that international travel is all glamour.

@robconery can copy this directly into the book.
