### ISSUE TITLE
Possible typo in Post mortem segment of chapter "Here’s everything that goes into a massive international speaking trip"

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#53]
## Where'd you find this? Page number from PDF would be helpful
376

## What's the problem? 
Not sure what it should be, but `before` seems the wrong word, perhaps between?

This is what I read:
```
I've stayed in 10 hotels and taken 10 flights consuming 54 hours of flight time
(that's not including all the waiting time and transiting before airports)
```

## How are you reading the book?
Windows 11 PDF v0.1

**Comment by troyhunt** [comment]
Good find, fixed in source, over to @robconery to fix in the book.
