### ISSUE TITLE
missing apostrophe? its -> it's

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#57]
pdf version 001 page 260, reading with Edge on Windows 11

This is what I read: 
>**its** allowed me to re-read this 

This is what I think it should be:
>**it's** allowed me to re-read this

or perhaps:
>**it** allowed me to re-read this

**Comment by troyhunt** [comment]
Agree with:

> as it allowed me to re-read this

Fixed in source, over to @robconery for the book.
