### ISSUE TITLE
has -> have

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#58]
pdf version 001 page 470, reading with Edge on Windows 11

This is what I read: 
>there **has** usually been many hours invested

This is what I think it should be:
>there **have** usually been many hours invested

**Comment by troyhunt** [comment]
I'm on the fence with this one; in my head, either works and to make it worse, Word grammar check doesn't complain about either version 🤷‍♂️ Without a definitive answer, I'm going to close and leave as is.
