### ISSUE TITLE
Capitalisation of Lego

### ISSUE THREAD

**Issue by aushades** [robconery/troys-book#6]
## Where'd you find this? Page number from PDF would be helpful
Editor's Note, page iv from the PDF.

## What's the problem? 

This is what I read:
```md
// Maybe we could go wakeboarding on his boat or I could build some lego things with his kids.
```

This is what I think it should be:
```md
//Maybe we could go wakeboarding on his boat or I could build some **L**ego things with his kids.
```
## How are you reading the book?
Windows 10, PDF, book version 0.1

I believe the 'L' for Lego should be capitalised as it is the name of the company.

**Comment by troyhunt** [comment]
Or is it "LEGO", being the stylised version of the name? https://en.wikipedia.org/wiki/Lego

As if @robconery didn't already go through enough pain learning Australian English, now he's dealing with the capitalisation of a Danish toy maker 🤣 At least he didn't say "legos"!

**Comment by robconery** [comment]
Ha ha - I went with the capped version :).
