### ISSUE TITLE
capitalise "Have I been pwned (HIBP)"

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#61]
pdf version 001 page 240, reading with Edge on Windows 11

This is what I read: 
>Have I **been pwned** (HIBP)

This is what I think it should be:
>Have I **Been Pwned** (HIBP)

ditto on page 270, 277 and 388
A trivial issue for sure, but HIBP deserves special care in this book

**Comment by troyhunt** [comment]
For a while there, I oscillated around casing, spacing and the use of a question mark after the name. I think we can leave this as is, it's part of the history of the name now 🙂
