### ISSUE TITLE
typo: is -> in

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#64]
pdf version 001 page 279, reading with Edge on Windows 11

This is what I read:
> I can go from the car to sitting in the domestic lounge **is** 5 minutes tops

This is what I think it should be:
> I can go from the car to sitting in the domestic lounge **in** 5 minutes tops

**Comment by troyhunt** [comment]
Already fixed here: https://github.com/robconery/troys-book/issues/5
