### ISSUE TITLE
Congress - Comments - Extra 's'

### ISSUE THREAD

**Issue by skipishere** [robconery/troys-book#65]
## Where'd you find this? Page number from PDF would be helpful
438

## What's the problem? 
`starts` instead of `start`

This is what I read:
```
So the question is, what are we going to do about it? I think it's high time that companies
starts evaluating their security practices and operating system developers starting thinking
secure by default in their engineering schemes
```

This is what I think it should be:
```
So the question is, what are we going to do about it? I think it's high time that companies
start evaluating their security practices and operating system developers starting thinking
secure by default in their engineering schemes
```
## How are you reading the book?
Windows 11 PDF v0.1

**Comment by skipishere** [comment]
I have just realised this was in the Comments section of the blog post (even though I typed that in the title) I know in a previous issue you mentioned not correcting these. 🤦

**Comment by troyhunt** [comment]
Yep, correct, closing now.
