### ISSUE TITLE
about thing (things*) like entropy and reuse

### ISSUE THREAD

**Issue by Cyber246** [robconery/troys-book#7]
![4E9ED1E2-F7D5-44D9-BF82-99D4AB91ACA7](https://user-images.githubusercontent.com/112099682/187031715-34d74515-1f86-4bfb-9ea2-4cf248a2c2b4.jpeg)

**Comment by troyhunt** [comment]
Thanks @Cyber246, now fixed in the source post and @robconery will roll it into a later release of the book as it's old content.

**Comment by robconery** [comment]
Fixed!
