### ISSUE TITLE
two more typos

### ISSUE THREAD

**Issue by robloh** [robconery/troys-book#74]
## Where'd you find this? Page number from PDF would be helpful
page 215 & page 244

## What's the problem? 

This is what I read:
```md
spectrum as I possible could
```

This is what I think it should be:
```md
spectrum as I possibly could
```

This is what I read:
```md
I just haven't see their message
```

This is what I think it should be:
```md
I just haven't seen their message
```
## How are you reading the book?
PDF v0.1

**Comment by robconery** [comment]
Thanks...!
