### ISSUE TITLE
Metadata is incorrect.

### ISSUE THREAD

**Issue by Absoblogginlutely** [robconery/troys-book#8]
Purchased the book today and the Metadata that gets displayed (in Calibre at least) for the epub version has wrong information.
It would be nice if the Title, Author and Publisher were correct
Screenshot attached to show what it looks like with possible changes.  
![image](https://user-images.githubusercontent.com/21364480/187074716-b2b59d5b-d632-4880-93b9-d05c4cb6dc0c.png)

**Comment by robconery** [comment]
Thanks - I _think_ I got it right on this try :).
