### ISSUE TITLE
singular -> plural: activity -> activities

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#80]
pdf version 001 page 494, reading with Edge on Windows 11

This is what I read: 
>a whole bunch of highly illegal **activity** that has harmed ...

This is what I think it should be:
>a whole bunch of highly illegal **activities** that has harmed ...

The second verb could be **has** (the bunch has harmed) or **have** (the activities have harmed), depending on what you want to say.

**Comment by troyhunt** [comment]
I'm satisfied the singular is still grammatically correct in this instance.
