### ISSUE TITLE
Typo: Troy gets a lot of flack

### ISSUE THREAD

**Issue by rose-a** [robconery/troys-book#9]
## Where'd you find this? Page number from PDF would be helpful
Page *V*

## What's the problem? 

This is what I read:
```md
Troy gets a lot of flack from various corners [...]
```

This is what I think it should be:
```md
Troy gets a lot of flak from various corners [...]
```
## How are you reading the book?
Please let me know the OS and format (epub/PDF/kindle) and if you can, the version of the book (it's on the front cover)

epub, V0.1

**Comment by robconery** [comment]
Thanks - that's a common problem apparently and one I didn't know about until today! @troyhunt  there's a `flack` mispelling in one of your posts too - the Online Abuse one - I corrected in book but you might want to do it in the post too for parity.

**Comment by troyhunt** [comment]
Good one, now fixed in that post.
