### ISSUE TITLE
Use capital "K" for thousands

### ISSUE THREAD

**Issue by mrutgers** [robconery/troys-book#95]
Use capital "K" for thousands

pdf version 001 page 744, reading with Edge on Windows 11

This is what I read: 
>there are **120k** people monitoring domains

This is what I think it should be:
>there are **120K** people monitoring domains

On the same page: 
>**230k** searches
>**150k** unique visitors

The odd occurrence is fair enough, but three on one page?

**Comment by troyhunt** [comment]
I'm gonna go with "a bit too pedantic" on this one 🙂
